### PR TITLE
Provide a fix for the hltGetConfiguration issue in CMSSW_8_0_X, X<9

### PR DESCRIPTION
**Pull request by mmusich**
@franzoni @bajarang trying to make the patched version a littel bit less ugly.
Didn't test it. @bajarang can you check the logic as well?

### CODE REVIEW

**Comment by bajarang** [comment]
Looking into the log for week 23 ECal Transparency submission's, I found even for "HLT_release": "CMSSW_8_0_8_patch2", condDatasetSubmitter_patch2.py script must be used.

**Comment by mmusich** [comment]
Hi @Bajarang, yes, so is this logic:

```
 +    return int( theRelease.split("_")[2] ) < 1  and int( theRelease.split("_")[3] ) >= 9 
```

inaccurate?
Marco

**Comment by bajarang** [comment]
@mmusich : My bad, your logic is correct.

**Comment by franzoni** [comment]
ciao @mmusich @bajarang 
by reading the code I gather that if we merge this we'll be able to handle the patch/no-patch case for all releases.

@bajarang 
it would be great if you could make 2 tests using:
- a release where we know the patch is required
- another one where it's not

**Pull request merged**
