### PR TITLE
can differentiate between 800 and 80X where X>=1

### PR DESCRIPTION
**Pull request by bajarang**
Now we can differentiate between the CMSSW release 8_0_0 and 8_0_X where X>=1

### CODE REVIEW

**Comment by franzoni** [comment]
hello Bajarag, I don't think that how you've implemented the check is generally correct.
For instance, 8_1_1 will match the condition, which should not.
The check on the second and third figure should be conditional to the first figure being 8.

Examples:
7_6_anything should return true
8_0_0 should return true
8_0_1 should return false
8_1_1 should return false

**Comment by bajarang** [comment]
Yes, you are right. I missed that. 
Now I have pushed the corrected condDatasetSubmitter.py . 
Please have a look.

**Comment by franzoni** [comment]
hello Bajarang,
we're getting closer. I believe 9_0_0 will pass the selection, which should not.
Can you take a further look ?

**Comment by bajarang** [comment]
I hope this time its Ok.

**Comment by franzoni** [comment]
hello @bajarang 
the logic of your last commit is correct.
However, there are syntax errors stemming from unmatched parenthesis.

I believe this is what you intended to commit :

```
def isCMSSWBeforeEight( theRelease ):
    if theRelease == None :
        raise ValueError('theRelease is set to %s and yet, it seems to be required. ERRROR.' % (theRelease))
    if int(theRelease.split("_")[1]) < 8 :
        return True
    elif int(theRelease.split("_")[1]) == 8 :
         return int( theRelease.split("_")[2] ) < 1  and int( theRelease.split("_")[3] ) < 1
    else :
         return False
```

?

Whenever you release code, it's good practice testing it injecting into it a few known cases to verifying the outcome. Either by running the full condDatasetSubmitter.py or at least using the ipython https://ipython.readthedocs.org/en/stable/

**Comment by franzoni** [comment]
superseded by PR #4

**Pull request closed without merging**
