### PR TITLE
Added time to processing_string and also sliced the label

### PR DESCRIPTION
**Pull request by bajarang**
@franzoni  Please take a look if the modifications in the processing_string are ok

### CODE REVIEW

**Comment by franzoni** [comment]
thanks @bajarang 

We also wanted to shorten these labels:

HLTreference => HLTref
HLTnewconditions => HLTnewcond
[and the equivalent for prompt]

do you think you may add such modification ?

**Comment by franzoni** [comment]
@mmusich

**Comment by bajarang** [comment]
@franzoni @mmusich Here is a sample of processing_string I get now 
1. 2016_07_21_07_06_HLTref_80X_dataRun2_HLT_v12
2. 2016_07_21_07_06_HLTnewcond_80X_dataRun2_HLTValidation_ECALTransp_w29_2016
3. 2016_07_21_11_09_PRref_80X_dataRun2_Prompt_v9
4. 2016_07_21_11_09_PRnewcond_80X_dataRun2_PromptValidation_ECALPed_w28_2016

**Comment by mmusich** [comment]
Hi @bajarang, 

```
$ echo 2016_07_21_11_09_PRnewcond_80X_dataRun2_PromptValidation_ECALPed_w28_2016 | wc
      1       1      74
```

looks good to me (we have some 20 chars spare)

**Comment by franzoni** [comment]
Thanks @bajarang @mmusich  !

**Pull request merged**
